notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install pyenv-win
        - pyenv install 3.8
        - pyenv rehash
        - pyenv global 3.8
script:
  - wget https://raw.githubusercontent.com/reity/canaries/master/canaries/canaries.py
  - python -V
  - python test.py
