notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install 3.8
        - pyenv rehash
        - pyenv global 3.8
script:
  - wget https://raw.githubusercontent.com/reity/canaries/master/canaries/canaries.py
  - python -V
  - python test.py
